import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Statement | CheckinHUB",
  description: "CheckinHUB privacy statement – how we collect, use, and protect your information.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[var(--color-bg)]">
      <header className="border-b border-[var(--color-border)] bg-[var(--color-bg-elevated)]">
        <div className="mx-auto max-w-3xl px-4 py-4">
          <Link href="/" className="text-sm text-[var(--color-primary)] hover:underline">
            ← Back to CheckinHUB
          </Link>
          <h1 className="mt-2 text-2xl font-semibold text-[var(--color-text)]">
            Privacy Statement
          </h1>
          <p className="mt-1 text-sm text-[var(--color-text-muted)]">
            Last updated: February 2026
          </p>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-8">
        <article className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-sm text-[var(--color-text-secondary)]">
          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              1. Who we are
            </h2>
            <p>
              CheckinHUB is a coach–client check-in and progress platform. Your coach (or the organisation that invited you) operates your use of the platform. This privacy statement describes how we collect, use, and protect your information when you use CheckinHUB.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              2. Information we collect
            </h2>
            <p className="mb-2">We collect information you provide and data generated by your use of the service:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong className="text-[var(--color-text)]">Account information:</strong> name, email address, phone (optional), timezone, and password (stored securely).</li>
              <li><strong className="text-[var(--color-text)]">Check-in data:</strong> your responses to check-in questions, scores, and any notes you submit.</li>
              <li><strong className="text-[var(--color-text)]">Coach feedback:</strong> feedback, reviews, and notes your coach adds to your check-ins.</li>
              <li><strong className="text-[var(--color-text)]">Progress data:</strong> measurements, goals, progress photos, and related content you upload or enter.</li>
              <li><strong className="text-[var(--color-text)]">Payment information:</strong> when payments are used, billing is processed by a third-party payment provider; we may store payment status and related identifiers, not your full card details.</li>
              <li><strong className="text-[var(--color-text)]">Usage data:</strong> such as when you sign in or view content, to operate and improve the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              3. How we use your information
            </h2>
            <p className="mb-2">We use your information to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Provide and maintain the CheckinHUB service (check-ins, feedback, progress tracking).</li>
              <li>Allow your coach to view your check-ins, scores, and progress and to add feedback.</li>
              <li>Process payments where applicable (via our payment provider).</li>
              <li>Send you service-related messages (e.g. reminders, notifications you opt into).</li>
              <li>Improve the platform, fix issues, and comply with legal obligations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              4. Storage and security
            </h2>
            <p>
              Your data is stored in secure cloud systems. We use industry-standard measures to protect your information. Access to your data is limited to you, your coach, and the platform as needed to run the service. We do not sell your personal information.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              5. Third-party services
            </h2>
            <p>
              We use trusted third-party services to run CheckinHUB (e.g. hosting, authentication, and payment processing). These providers process data on our behalf under strict agreements and only for the purposes of providing the service. Their own privacy policies may also apply (e.g. Stripe for payments).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              6. Your rights
            </h2>
            <p className="mb-2">Depending on where you live, you may have the right to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Access the personal data we hold about you.</li>
              <li>Request correction of inaccurate data.</li>
              <li>Request deletion of your data (subject to legal and contractual needs).</li>
              <li>Object to or restrict certain processing.</li>
              <li>Withdraw consent where we rely on it.</li>
            </ul>
            <p className="mt-2">
              To exercise these rights or ask questions about your data, contact your coach or the organisation that provided you access to CheckinHUB. You may also have the right to lodge a complaint with a supervisory authority in your country.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              7. Data retention
            </h2>
            <p>
              We retain your data for as long as your account is active and as needed to provide the service, resolve disputes, and comply with legal obligations. When you or your coach closes an account, we may retain some data for a limited period for legal or operational reasons before secure deletion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              8. Changes to this statement
            </h2>
            <p>
              We may update this privacy statement from time to time. We will post the updated version on this page and update the &quot;Last updated&quot; date. Continued use of CheckinHUB after changes constitutes acceptance of the updated statement. For material changes, we may notify you via the platform or email where appropriate.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--color-text)] mb-2">
              9. Contact
            </h2>
            <p>
              For privacy-related questions or requests, contact your coach or the organisation that invited you to CheckinHUB. For technical or platform-related support, use the contact details provided to you when you joined the service.
            </p>
          </section>
        </article>

        <p className="mt-10 pt-6 border-t border-[var(--color-border)] text-center">
          <Link href="/" className="text-[var(--color-primary)] hover:underline">
            Return to CheckinHUB
          </Link>
        </p>
      </main>
    </div>
  );
}
